# Generated by Django 3.2.8 on 2022-03-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория фото')),
            ],
            options={
                'verbose_name': 'Категория фото',
                'verbose_name_plural': 'Категории фото',
            },
        ),
        migrations.CreateModel(
            name='PhotostreamForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_photo', models.URLField(max_length=255, verbose_name='Ссылка на фото')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки фото')),
                ('status_worked_out', models.BooleanField(default=False, verbose_name='Зачёт (Да/Нет)')),
                ('date_correction', models.DateField(blank=True, null=True, verbose_name='Дата исправления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='Адрес ТТ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photostream.categoryphoto', verbose_name='Категория фото')),
                ('dsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.dsm', verbose_name='Территория DSM')),
                ('esr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.esr', verbose_name='Территория ESR')),
                ('tsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tsm', verbose_name='Территория TSM')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tt', verbose_name='Наименование ТТ')),
            ],
            options={
                'verbose_name': 'Фотопоток',
                'verbose_name_plural': 'Фотопоток',
                'ordering': ['-created_at'],
            },
        ),
    ]
