# Generated by Django 3.2.8 on 2022-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photostreamform',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес ТТ'),
        ),
        migrations.AlterField(
            model_name='photostreamform',
            name='tt',
            field=models.CharField(max_length=255, verbose_name='Наименование ТТ'),
        ),
    ]
