# Generated by Django 3.2.8 on 2022-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostream', '0002_auto_20220330_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photostreamform',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оценки фото'),
        ),
        migrations.AlterField(
            model_name='photostreamform',
            name='url_photo',
            field=models.URLField(max_length=255, unique=True, verbose_name='Ссылка на фото'),
        ),
    ]
