# Generated by Django 3.2.8 on 2022-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nkz', models.FileField(blank=True, upload_to='remains/nkz', verbose_name='Главный склад Новокузнецк')),
                ('nsk', models.FileField(blank=True, upload_to='remains/nsk', verbose_name='Главный склад Новосибирск')),
                ('omsk', models.FileField(blank=True, upload_to='remains/omsk', verbose_name='Главный склад Омск')),
                ('krs', models.FileField(blank=True, upload_to='remains/krs', verbose_name='Главный склад Красноярск')),
                ('abk', models.FileField(blank=True, upload_to='remains/abk', verbose_name='Главный склад Абакан')),
            ],
            options={
                'verbose_name': 'Загрузка остатков',
                'verbose_name_plural': 'Загрузка остатков',
            },
        ),
    ]
