# Generated by Django 3.2.8 on 2022-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remains', '0003_remains_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainsfile',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата загрузки'),
        ),
    ]
