# Generated by Django 3.2.8 on 2022-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remains', '0004_remainsfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='remains',
            name='topx',
            field=models.CharField(db_column='TOPX', default='topx', max_length=255, verbose_name='TOPX'),
            preserve_default=False,
        ),
    ]
