# Generated by Django 3.2.8 on 2022-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remains', '0007_auto_20220705_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbc', models.CharField(db_column='DBC', max_length=255, verbose_name='DBC')),
                ('code_nestle', models.IntegerField(db_column='код товара', verbose_name='Код товара')),
                ('dbc_name', models.CharField(db_column='наименование DBC', max_length=255, verbose_name='Наименование DBC')),
                ('launch', models.CharField(db_column='launch', max_length=255, verbose_name='Новая позиция')),
            ],
            options={
                'verbose_name': 'Позиция на запуск',
                'verbose_name_plural': 'Позиции на запуски',
            },
        ),
        migrations.AddField(
            model_name='remains',
            name='launch',
            field=models.CharField(db_column='launch', default='', max_length=255, verbose_name='Новая позиция'),
            preserve_default=False,
        ),
    ]
