# Generated by Django 3.2.8 on 2022-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbc', models.CharField(db_column='DBC', max_length=10, verbose_name='DBC')),
                ('rev_group_top', models.CharField(db_column='RevGroupTopX', max_length=255, verbose_name='Группа ревизии ТопХ')),
                ('min_sell', models.IntegerField(db_column='Min_sell', verbose_name='Порог зачета')),
                ('dbc_name', models.CharField(db_column='наименование DBC', max_length=255, verbose_name='Наименование DBC')),
            ],
            options={
                'verbose_name': 'Категория ТопХ',
                'verbose_name_plural': 'Категории ТопХ',
                'ordering': ['rev_group_top'],
            },
        ),
        migrations.CreateModel(
            name='VolumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_column='группа', max_length=255, verbose_name='Группа')),
                ('rev_pre_group', models.CharField(db_column='RevPreGroup', max_length=255, verbose_name='Подгруппа ревизии')),
                ('rev_group', models.CharField(db_column='Revision Group', max_length=255, verbose_name='Группа ревизии')),
            ],
            options={
                'verbose_name': 'Категория объема',
                'verbose_name_plural': 'Категории объема',
                'ordering': ['group'],
            },
        ),
    ]
