# Generated by Django 3.2.8 on 2022-03-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report07',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_column='Площадка', max_length=255, verbose_name='Площадка')),
                ('rsm', models.CharField(db_column='RSM', max_length=255, verbose_name='RSM')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='ESR')),
                ('tier', models.CharField(db_column='Tier', max_length=255, verbose_name='Tier')),
                ('stream_tk', models.CharField(db_column='Стрим ТК', max_length=255, verbose_name='Стрим ТК')),
                ('code_tt_kis', models.CharField(db_column='код ТТ КИС', max_length=255, verbose_name='Код ТТ КИС')),
                ('name_tt', models.CharField(db_column='наименование ТТ', max_length=255, verbose_name='Наименование ТТ')),
                ('address_tt', models.CharField(db_column='адрес ТТ', max_length=255, verbose_name='Адрес ТТ')),
                ('specialization_tt', models.CharField(db_column='Специализация ТТ', max_length=255, verbose_name='Специализация ТТ')),
                ('channel_tt', models.CharField(db_column='канал ТТ', max_length=255, verbose_name='Канал ТТ')),
                ('key_retail', models.CharField(db_column='Ключевая розница', max_length=255, verbose_name='Ключевая розница')),
                ('key_whs', models.CharField(db_column='Ключевой опт', max_length=255, verbose_name='Ключевой опт')),
                ('network', models.CharField(db_column='сеть', max_length=255, verbose_name='Сеть')),
                ('document_number', models.CharField(db_column='номер документа', max_length=255, verbose_name='Номер документа')),
                ('document_date', models.CharField(db_column='дата документа', max_length=255, verbose_name='Дата документа')),
                ('date_shipment', models.CharField(db_column='дата отгрузки', max_length=255, verbose_name='Дата отгрузки')),
                ('document_type', models.CharField(db_column='тип документа', max_length=255, verbose_name='Тип документа')),
                ('month', models.IntegerField(db_column='месяц', verbose_name='Месяц')),
                ('week', models.IntegerField(db_column='Неделя', verbose_name='Неделя')),
                ('day', models.IntegerField(db_column='день', verbose_name='День')),
                ('dbc', models.CharField(db_column='DBC', max_length=255, verbose_name='DBC')),
                ('dbc_name', models.CharField(db_column='наименование DBC', max_length=255, verbose_name='Наименование DBC')),
                ('code_nestle', models.IntegerField(db_column='код товара', verbose_name='Код товара')),
                ('product', models.CharField(db_column='товар', max_length=255, verbose_name='Товар')),
                ('category', models.CharField(db_column='категория', max_length=255, verbose_name='Категория')),
                ('group', models.CharField(db_column='группа', max_length=255, verbose_name='Группа')),
                ('pre_group', models.CharField(db_column='подгруппа', max_length=255, verbose_name='Подгруппа')),
                ('sum_sell', models.FloatField(db_column='Сумма продаж (руб.)', verbose_name='Сумма продаж')),
                ('sum_sell_no_nds', models.FloatField(db_column='Сумма продаж БЕЗ НДС (руб.)', verbose_name='Сумма продаж БЕЗ НДС')),
                ('count_piece', models.IntegerField(db_column='Количество (шт.)', verbose_name='Количество')),
                ('weight', models.FloatField(db_column='Вес (кг.)', verbose_name='Вес (кг.)')),
                ('price', models.FloatField(db_column='Price', verbose_name='Цена')),
                ('rev_pre_group', models.CharField(db_column='RevPreGroup', max_length=255, verbose_name='Подгруппа ревизии')),
                ('rev_group', models.CharField(db_column='Revision Group', max_length=255, verbose_name='Группа ревизии')),
                ('rev_group_top', models.CharField(db_column='RevGroupTopX', max_length=255, verbose_name='Группа ревизии ТопХ')),
                ('min_sell', models.FloatField(db_column='Min_sell', verbose_name='Порог зачета')),
                ('topx', models.CharField(db_column='TOP', max_length=255, verbose_name='Статус ТопХ')),
            ],
            options={
                'verbose_name': 'Отчет по продажам',
                'verbose_name_plural': 'Отчет по продажам',
                'ordering': ['region'],
            },
        ),
    ]
