# Generated by Django 3.2.8 on 2022-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_report07'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report07',
            name='date_shipment',
            field=models.DateField(db_column='дата отгрузки', verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='report07',
            name='document_date',
            field=models.DateField(db_column='дата документа', verbose_name='Дата документа'),
        ),
    ]
