# Generated by Django 3.2.8 on 2022-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_reportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report07',
            name='virtual',
            field=models.CharField(db_column='виртуальность', default=111, max_length=255, verbose_name='Виртуальность'),
            preserve_default=False,
        ),
    ]
