# Generated by Django 3.2.8 on 2022-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_report07_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumePlanTSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
                ('tier', models.CharField(db_column='Tier', max_length=255, verbose_name='Tier')),
                ('territory', models.CharField(db_column='Territory', max_length=255, verbose_name='Territory')),
                ('rev_pre_group', models.CharField(db_column='RevPreGroup', max_length=255, verbose_name='Подгруппа ревизии')),
                ('target', models.IntegerField(db_column='Target', verbose_name='План(руб.)')),
                ('group', models.CharField(db_column='группа', max_length=255, verbose_name='Группа')),
                ('rev_group', models.CharField(db_column='Revision Group', max_length=255, verbose_name='Группа ревизии')),
            ],
        ),
    ]
