# Generated by Django 3.2.8 on 2022-04-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_volumeplantsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumeplantsm',
            name='group',
        ),
    ]
