# Generated by Django 3.2.8 on 2022-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_remove_volumeplantsm_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumePlanESR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='ESR')),
                ('tier', models.CharField(db_column='Tier', max_length=255, verbose_name='Tier')),
                ('rev_pre_group', models.CharField(db_column='RevPreGroup', max_length=255, verbose_name='Подгруппа ревизии')),
                ('rev_group', models.CharField(db_column='Revision Group', max_length=255, verbose_name='Группа ревизии')),
                ('target', models.IntegerField(db_column='Target', verbose_name='План(руб.)')),
            ],
        ),
        migrations.RemoveField(
            model_name='volumeplantsm',
            name='territory',
        ),
    ]
