# Generated by Django 3.2.8 on 2022-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20220402_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата загрузки')),
                ('plan', models.FileField(upload_to='indicators/xls_plan', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Загрузка плана',
                'verbose_name_plural': 'Загрузка планов',
            },
        ),
    ]
