# Generated by Django 3.2.8 on 2022-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_planfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='Категория', max_length=255, verbose_name='Категория')),
                ('dbc', models.CharField(db_column='DBC', max_length=255, verbose_name='DBC')),
                ('dbc_name', models.CharField(db_column='наименование DBC', max_length=255, verbose_name='Наименование DBC')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='ESR')),
                ('target', models.IntegerField(db_column='Target', verbose_name='План(руб.)')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
            ],
        ),
    ]
