# Generated by Django 3.2.8 on 2022-04-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_topplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='ESR')),
                ('target', models.IntegerField(db_column='Target', verbose_name='План(ТТ)')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
            ],
        ),
        migrations.AlterField(
            model_name='topplan',
            name='target',
            field=models.IntegerField(db_column='Target', verbose_name='План(sku)'),
        ),
    ]
