# Generated by Django 3.2.8 on 2022-04-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20220403_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_column='канал ТТ', max_length=255, verbose_name='Канал ТТ')),
            ],
            options={
                'verbose_name': 'Канал ТТ',
                'verbose_name_plural': 'Каналы ТТ',
            },
        ),
        migrations.CreateModel(
            name='DBCName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBC_name', models.CharField(db_column='наименование DBC', max_length=255, unique=True, verbose_name='Наименование DBC')),
            ],
            options={
                'verbose_name': 'Наименование DBC запуска',
                'verbose_name_plural': 'Наименования DBC запусков',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяца',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(db_column='Tier', max_length=255, verbose_name='Tier')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tier',
            },
        ),
        migrations.CreateModel(
            name='IdeaToLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_column='task', max_length=255, verbose_name='Задача')),
                ('description', models.TextField(db_column='description', default='', verbose_name='Описание')),
                ('min_threshold', models.IntegerField(db_column='min_threshold', default=0, verbose_name='Минимальный порог зачёта')),
                ('func_launch', models.CharField(max_length=255, verbose_name='Метод подсчета')),
                ('channel', models.ManyToManyField(to='indicators.ChannelTT', verbose_name='Каналы ТТ')),
                ('dbc', models.ManyToManyField(to='indicators.DBCName', verbose_name='Участвующие позиции')),
                ('months', models.ManyToManyField(to='indicators.Month', verbose_name='Период')),
                ('tier', models.ManyToManyField(to='indicators.Tier', verbose_name='Tier')),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
            },
        ),
    ]
