# Generated by Django 3.2.8 on 2022-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_channeltt_dbcname_ideatolaunch_month_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageplan',
            name='rsm',
            field=models.CharField(db_column='RSM', default='', max_length=255, verbose_name='RSM'),
            preserve_default=False,
        ),
    ]
