# Generated by Django 3.2.8 on 2022-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_coverageplan_rsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report145',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_column='Наименование площадки', max_length=255, verbose_name='Площадка')),
                ('rsm', models.CharField(db_column='RSM', max_length=255, verbose_name='RSM')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
                ('esr', models.CharField(db_column='Имя ESR', max_length=255, verbose_name='ESR')),
                ('code_tt_kis', models.CharField(db_column='XCRM GUID', max_length=255, verbose_name='Код ТТ КИС')),
                ('name_tt', models.CharField(db_column='Название ТТ', max_length=255, verbose_name='Наименование ТТ')),
                ('address_tt', models.CharField(db_column='Адрес', max_length=255, verbose_name='Адрес ТТ')),
                ('channel_tt', models.CharField(db_column='Канал ТТ', max_length=255, verbose_name='Канал ТТ')),
                ('tier', models.CharField(db_column='Tier', max_length=255, verbose_name='Tier')),
                ('category', models.CharField(db_column='Ассортимент', max_length=255, verbose_name='Категория')),
                ('dbc', models.CharField(db_column='DBC ID', max_length=255, verbose_name='DBC')),
                ('dbc_name', models.CharField(db_column='Наименование DBC', max_length=255, verbose_name='Наименование DBC')),
                ('month', models.CharField(db_column='Месяц', max_length=255, verbose_name='Месяц')),
                ('sum_sell', models.FloatField(db_column='Объем продаж точки', verbose_name='Сумма продаж')),
            ],
            options={
                'verbose_name': '145й отчет усилений',
                'verbose_name_plural': '145й отчет усилений',
                'ordering': ['region'],
            },
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='abk',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='krs',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='nkz',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='nsk',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='omsk',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='abk_07',
            field=models.FileField(blank=True, upload_to='indicators/report07', verbose_name='Абакан_07'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='abk_145',
            field=models.FileField(blank=True, upload_to='indicators/report145', verbose_name='Абакан_145'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='krs_07',
            field=models.FileField(blank=True, upload_to='indicators/report07', verbose_name='Красноярск_07'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='krs_145',
            field=models.FileField(blank=True, upload_to='indicators/report145', verbose_name='Красноярск_145'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='nkz_07',
            field=models.FileField(blank=True, upload_to='indicators/report07', verbose_name='Новокузнецк_07'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='nkz_145',
            field=models.FileField(blank=True, upload_to='indicators/report145', verbose_name='Новокузнецк_145'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='nsk_07',
            field=models.FileField(blank=True, upload_to='indicators/report07', verbose_name='Новосибирск_07'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='nsk_145',
            field=models.FileField(blank=True, upload_to='indicators/report145', verbose_name='Новосибирск_145'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='omsk_07',
            field=models.FileField(blank=True, upload_to='indicators/report07', verbose_name='Омск_07'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='omsk_145',
            field=models.FileField(blank=True, upload_to='indicators/report145', verbose_name='Омск_145'),
        ),
    ]
