# Generated by Django 3.2.8 on 2022-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20220423_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbc_name', models.CharField(db_column='наименование DBC', max_length=255, verbose_name='Наименование DBC')),
                ('distr_task', models.CharField(db_column='distr_task', max_length=255, verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Задача по SKU',
                'verbose_name_plural': 'Задачи по SKU',
            },
        ),
    ]
