# Generated by Django 3.2.8 on 2022-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_auto_20220430_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report770',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_column='Месяц', max_length=255, verbose_name='Месяц')),
                ('date_foto', models.DateField(db_column='Дата документа', verbose_name='Дата документа')),
                ('channel_tt', models.CharField(db_column='Канал ТТ', max_length=255, verbose_name='Канал ТТ')),
                ('network', models.CharField(db_column='Вывеска сети', max_length=255, verbose_name='Вывеска сети')),
                ('region', models.CharField(db_column='Площадка', max_length=255, verbose_name='Площадка')),
                ('rsm', models.CharField(db_column='RSM', max_length=255, verbose_name='RSM')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='TSM')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='ESR')),
                ('code_tt', models.CharField(db_column='Код ТТ', max_length=255, verbose_name='Код ТТ')),
                ('name_tt', models.CharField(db_column='Название ТТ', max_length=255, verbose_name='Название ТТ')),
                ('address_tt', models.CharField(db_column='Адрес ТТ', max_length=255, verbose_name='Адрес ТТ')),
                ('category', models.CharField(db_column='Категория', max_length=255, verbose_name='Категория')),
                ('status_price', models.CharField(db_column='Статус снижения цены', max_length=10, verbose_name='Статус снижения цены')),
                ('standart_shop', models.CharField(db_column='Стандартный магазин', max_length=10, verbose_name='Стандартный магазин')),
                ('foto_url', models.CharField(db_column='URL', max_length=255, verbose_name='URL')),
                ('status', models.IntegerField(db_column='Статус', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отчет по фотопотоку',
                'verbose_name_plural': 'Отчет по фотопотоку',
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Report770File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата загрузки')),
                ('plan', models.FileField(upload_to='indicators/report_770', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Загрузка 770го отчета',
                'verbose_name_plural': 'Загрузка 770го отчета',
            },
        ),
        migrations.AlterField(
            model_name='report145',
            name='address_tt',
            field=models.CharField(blank=True, db_column='Адрес', max_length=255, verbose_name='Адрес ТТ'),
        ),
        migrations.AlterField(
            model_name='report145',
            name='name_tt',
            field=models.CharField(blank=True, db_column='Название ТТ', max_length=255, verbose_name='Наименование ТТ'),
        ),
    ]
