# Generated by Django 3.2.8 on 2022-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20220601_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report145',
            name='dbc',
            field=models.CharField(blank=True, db_column='DBC ID', max_length=255, verbose_name='DBC'),
        ),
        migrations.AlterField(
            model_name='report145',
            name='dbc_name',
            field=models.CharField(blank=True, db_column='Наименование DBC', max_length=255, verbose_name='Наименование DBC'),
        ),
    ]
