# Generated by Django 3.2.8 on 2022-03-27 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='Территория DSM')),
            ],
            options={
                'verbose_name': 'Территория DSM',
                'verbose_name_plural': 'Территории DSM',
            },
        ),
        migrations.CreateModel(
            name='ESR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='Территория ESR')),
            ],
            options={
                'verbose_name': 'Территория ESR',
                'verbose_name_plural': 'Территории ESR',
            },
        ),
        migrations.CreateModel(
            name='TSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='Территория TSM')),
                ('dsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.dsm', verbose_name='Территория DSM')),
            ],
            options={
                'verbose_name': 'Территория TSM',
                'verbose_name_plural': 'Территории TSM',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/users', verbose_name='Аватар')),
                ('dsm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.dsm', verbose_name='Территория DSM')),
                ('esr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.esr', verbose_name='Территория ESR')),
                ('tsm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.tsm', verbose_name='Территория TSM')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.CharField(db_column='наименование ТТ', max_length=255, verbose_name='Наименование ТТ')),
                ('esr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.esr', verbose_name='Территория ESR')),
            ],
            options={
                'verbose_name': 'Наименование ТТ',
                'verbose_name_plural': 'Наименования ТТ',
            },
        ),
        migrations.AddField(
            model_name='esr',
            name='tsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tsm', verbose_name='Территория TSM'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_column='адрес ТТ', max_length=255, verbose_name='Адрес ТТ')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tt', verbose_name='Наименование ТТ')),
            ],
            options={
                'verbose_name': 'Адрес ТТ',
                'verbose_name_plural': 'Адреса ТТ',
            },
        ),
    ]
