# Generated by Django 3.2.8 on 2022-03-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='esr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.esr', verbose_name='Территория ESR'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tsm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.tsm', verbose_name='Территория TSM'),
        ),
    ]
