# Generated by Django 3.2.8 on 2022-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220327_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsm', models.CharField(db_column='DSM', max_length=255, verbose_name='Территория DSM')),
                ('tsm', models.CharField(db_column='TSM', max_length=255, verbose_name='Территория TSM')),
                ('esr', models.CharField(db_column='ESR', max_length=255, verbose_name='Территория ESR')),
            ],
            options={
                'verbose_name': 'Иерархия',
                'verbose_name_plural': 'Иерархия',
            },
        ),
    ]
