# Generated by Django 3.2.8 on 2022-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='rsm',
            field=models.CharField(db_column='RSM', default='123', max_length=255, verbose_name='Территория RSM'),
            preserve_default=False,
        ),
    ]
