# Generated by Django 3.2.8 on 2022-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hierarchy_rsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='kis_code',
            field=models.CharField(db_column='код ТТ КИС', default='', max_length=255, verbose_name='Код ТТ КИС'),
            preserve_default=False,
        ),
    ]
