# Generated by Django 3.2.8 on 2022-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_kis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='code_tt',
            field=models.CharField(db_column='код ТТ', default=1, max_length=255, verbose_name='код ТТ'),
            preserve_default=False,
        ),
    ]
