# Generated by Django 3.2.8 on 2022-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_code_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='day_route',
            field=models.CharField(db_column='day_route', default='ПН', max_length=255, verbose_name='День недели'),
            preserve_default=False,
        ),
    ]
