# Generated by Django 3.2.8 on 2022-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address_day_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='channel_tt',
            field=models.CharField(db_column='канал ТТ', default='', max_length=255, verbose_name='Канал ТТ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='tier',
            field=models.CharField(db_column='Tier', default='', max_length=255, verbose_name='Tier'),
            preserve_default=False,
        ),
    ]
