# Generated by Django 3.2.8 on 2022-06-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0019_auto_20220605_2113'),
        ('accounts', '0008_address_day_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitors', models.CharField(max_length=255, verbose_name='Конкуренты')),
            ],
            options={
                'verbose_name': 'Конкурент',
                'verbose_name_plural': 'Конкуренты',
            },
        ),
        migrations.CreateModel(
            name='PresenceNestle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenceNestle', models.CharField(max_length=255, verbose_name='Ассортимент Nestle')),
            ],
            options={
                'verbose_name': 'Ассортимент Nestle',
                'verbose_name_plural': 'Ассортимент Nestle',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporateBodyName', models.CharField(max_length=255, verbose_name='Наименование юр.лица')),
                ('taxIdentificationNumber', models.CharField(blank=True, max_length=10, verbose_name='ИНН')),
                ('count_tt', models.IntegerField(default=1, verbose_name='Кол-во ТТ')),
                ('contactName', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phoneNumber', models.CharField(blank=True, max_length=16, verbose_name='Номер телефона')),
                ('deliveryContract', models.BooleanField(default=False, verbose_name='Договор поставки с ООО КОНТИНЕНТ')),
                ('name_tt', models.CharField(max_length=255, verbose_name='Наименование ТТ')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('houseNumber', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('photo', models.ImageField(upload_to='outlet_photos/%Y/%m/%d', verbose_name='Фото вывески')),
                ('comment', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('dateConversation', models.DateTimeField(verbose_name='Дата следующего визита')),
                ('statusWorkedOut', models.CharField(choices=[('', 'Выбери'), ('Ассортимент не интересен', 'Ассортимент не интересен'), ('Не проходим по цене', 'Не проходим по цене'), ('Оставили прайс', 'Оставили прайс'), ('Заводим договор поставки', 'Заводим договор поставки'), ('Работаем', 'Работаем')], max_length=255, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('channel_tt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.channeltt', verbose_name='Канал ТТ')),
                ('competitors', models.ManyToManyField(default='Нет конкурентов', to='retail_census.Competitors')),
                ('dsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.dsm', verbose_name='Территория DSM')),
                ('esr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.esr', verbose_name='Территория ESR')),
                ('presenceNestle', models.ManyToManyField(default='Нет ассортимента Nestle', to='retail_census.PresenceNestle')),
                ('tsm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tsm', verbose_name='Территория TSM')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'ordering': ['-dateConversation'],
            },
        ),
    ]
